# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
                ('q4', models.FloatField()),
                ('q5', models.FloatField()),
            ],
        ),
    ]
