# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='q5',
        ),
        migrations.AddField(
            model_name='student',
            name='assign',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='el',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='eq1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='eq2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='eq3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='eq4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='lab',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ml',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mq1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mq2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mq3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='proj',
            field=models.FloatField(default=0),
        ),
    ]
